name: aushaadx
description: A new Flutter project.

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  image_picker: ^1.1.0
  google_mlkit_text_recognition: ^0.11.0  # ✅ Keep this
  flutter_local_notifications: ^18.0.1
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  http: ^1.1.0
  dio: ^5.3.2
  url_launcher: ^6.2.1
  geolocator: ^14.0.1
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  provider: ^6.1.1
  intl: ^0.20.2
  timezone: ^0.9.2
  cloud_firestore: ^5.6.9
  path_provider: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
